version: '3.4'

services:
  techgen:
    image: ${DOCKER_REGISTRY-}techgen
    build:
      context: .
      dockerfile: Techgen/Dockerfile
    ports:
      - "4200:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Connection=Data Source=/app/TechGen.db
