version: '3.7'

services:

  techgen_back:
    image: techgen_back
    container_name: techgen_back
    depends_on:
      - techgen_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=techgenback.db
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
  
  techgen_db:
    image: nouchka/sqlite3:latest
    container_name: techgen_db
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data