version: '3.7'

services:

  techgen_back:
    image: techgen_back
    container_name: techgen_back
    depends_on:
      - techgen_db
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile
  
  techgen_db:
    image: nouchka/sqlite3:latest
    container_name: techgen_db
    ports:
      - "8085:80"
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/